// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "Lijst blogposts",
  description: "Geeft blogposts terug, optioneel gefilterd op status of zoekterm in de titel.",
  inputSchema: {
    status: z.enum(["draft", "published", "archived"]).optional().describe("Filter op status."),
    search: z.string().trim().min(1).optional().describe("Zoekterm in de titel."),
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum aantal posts.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd." }], isError: true };
    }
    let query = supabaseForUser(ctx).from("blog_posts").select("id, title, slug, status, excerpt, published_at, updated_at, is_featured").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Haal blogpost op",
  description: "Haalt \xE9\xE9n blogpost op inclusief volledige inhoud, op slug of id.",
  inputSchema: {
    slug: z2.string().trim().min(1).optional().describe("Slug van de post."),
    id: z2.string().uuid().optional().describe("Id van de post.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd." }], isError: true };
    }
    if (!slug && !id) {
      return { content: [{ type: "text", text: "Geef een slug of id op." }], isError: true };
    }
    let query = supabaseForUser(ctx).from("blog_posts").select("*");
    query = id ? query.eq("id", id) : query.eq("slug", slug);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Geen blogpost gevonden." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z3 } from "npm:zod@^3.25.76";
var create_blog_post_default = defineTool3({
  name: "create_blog_post",
  title: "Maak blogpost",
  description: "Maakt een nieuwe blogpost aan, standaard als concept.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("Titel van de post."),
    slug: z3.string().trim().min(1).describe("URL-slug, kleine letters en streepjes."),
    content: z3.string().min(1).describe("Inhoud in markdown, zonder H1."),
    excerpt: z3.string().trim().optional().describe("Korte samenvatting."),
    meta_description: z3.string().trim().optional().describe("SEO meta description."),
    status: z3.enum(["draft", "published"]).default("draft").describe("Publicatiestatus.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, slug, content, excerpt, meta_description, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd." }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("blog_posts").insert({
      title,
      slug,
      content,
      excerpt,
      meta_description,
      status: status ?? "draft",
      author_id: ctx.getUserId(),
      published_at: status === "published" ? (/* @__PURE__ */ new Date()).toISOString() : null
    }).select("id, title, slug, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool4({
  name: "list_clients",
  title: "Lijst klanten",
  description: "Geeft de klanten (logo's) van B2BGroeiMachine terug met sector en website.",
  inputSchema: {
    only_visible: z4.boolean().default(true).describe("Alleen zichtbare klanten tonen."),
    limit: z4.number().int().min(1).max(100).default(50).describe("Maximum aantal klanten.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_visible, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd." }], isError: true };
    }
    let query = supabaseForUser(ctx).from("client_logos").select("id, name, domain, website, sector, description, is_visible, sort_order").order("sort_order", { ascending: true }).limit(limit ?? 50);
    if (only_visible !== false) query = query.eq("is_visible", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-contact-submissions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_contact_submissions_default = defineTool5({
  name: "list_contact_submissions",
  title: "Lijst contactaanvragen",
  description: "Geeft de meest recente aanvragen uit het contactformulier terug.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(20).describe("Maximum aantal aanvragen."),
    search: z5.string().trim().min(1).optional().describe("Zoekterm in naam of bedrijf.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd." }], isError: true };
    }
    let query = supabaseForUser(ctx).from("contact_submissions").select("id, name, email, company, phone, message, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.or(`name.ilike.%${search}%,company.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { submissions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "snymrcialncxkcsibkjv";
var mcp_default = defineMcp({
  name: "b2b-signal-based-system",
  title: "b2b signal based system",
  version: "0.1.0",
  instructions: "Tools voor B2BGroeiMachine: blogposts lezen en aanmaken, klanten opvragen en contactaanvragen bekijken. Alle acties draaien als de ingelogde gebruiker.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_blog_posts_default, get_blog_post_default, create_blog_post_default, list_clients_default, list_contact_submissions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
